# Numpy (Numerical Python)

## Introduction

NumPy is the fundamental package for scientific computing with Python. It contains among other things:

* a powerful N-dimensional array object

* sophisticated (broadcasting) functions

* tools for integrating C/C++ and Fortran code

* useful linear algebra, Fourier transform, and random number capabilities

Besides its obvious scientific uses, NumPy can also be used as an efficient multi-dimensional container of generic data. Arbitrary data-types can be defined. This allows NumPy to seamlessly and speedily integrate with a wide variety of databases.

* ndarray -> numpy arrayleri, n boyutlu array anlamına gelir. 

* 1 dim array -> vector  
* multiple dim array -> matrix

* numpy array -> not flexible; can take 1 type of data but more effective storage

In [1]:
a = [1,2,3]
b = [4,5,6]

ab = []

for i in range(0, len(a)):
    ab.append(a[i]*b[i])
    
ab

[4, 10, 18]

In [2]:
import numpy as np

c = np.array([1,2,3])
d = np.array([4,5,6])

c*d

array([ 4, 10, 18])

In [3]:
?np

Type:        module
String form: <module 'numpy' from '/anaconda3/lib/python3.7/site-packages/numpy/__init__.py'>
File:        /anaconda3/lib/python3.7/site-packages/numpy/__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://www.scipy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as `np`::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

U

In [4]:
who

a	 ab	 b	 c	 d	 i	 np	 


In [5]:
L = [1,2,"a",1.2]

In [6]:
[type(i) for i in L]

[int, int, str, float]

In [7]:
type(L[0])

int

# NumPy Array

## Creating array from a list

In [8]:
import numpy as np

f = np.array([12,33,4,5])

f

array([12, 33,  4,  5])

In [9]:
type(f)

numpy.ndarray

In [10]:
np.array([3.14, 4, 5, 1.2])

array([3.14, 4.  , 5.  , 1.2 ])

In [11]:
np.array([3.14, 4, 5, 1.2], dtype = 'float32')

array([3.14, 4.  , 5.  , 1.2 ], dtype=float32)

## Creating a particular array

**array containing only 0s or 1s:**

In [12]:
np.zeros(10, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [13]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

**array containing only a particular number:**

In [14]:
np.full((2,3), 9)

array([[9, 9, 9],
       [9, 9, 9]])

**array containing numbers between 0 and 10 increasing by twos:** 

In [15]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

**array containing 30 values between 0 and 1:**

In [16]:
np.linspace(0,1,30)

array([0.        , 0.03448276, 0.06896552, 0.10344828, 0.13793103,
       0.17241379, 0.20689655, 0.24137931, 0.27586207, 0.31034483,
       0.34482759, 0.37931034, 0.4137931 , 0.44827586, 0.48275862,
       0.51724138, 0.55172414, 0.5862069 , 0.62068966, 0.65517241,
       0.68965517, 0.72413793, 0.75862069, 0.79310345, 0.82758621,
       0.86206897, 0.89655172, 0.93103448, 0.96551724, 1.        ])

**array with mean = 0 and std dev = 1:**

In [17]:
np.random.normal(0,1, (3,4))

array([[-0.36346517, -0.01237764,  0.24896398,  1.26160652],
       [ 0.71984207,  0.71230413, -1.4355693 , -0.54174778],
       [-0.19320177,  1.10067393,  0.88092536,  0.32084631]])

In [18]:
?np.random.normal

Docstring:
normal(loc=0.0, scale=1.0, size=None)

Draw random samples from a normal (Gaussian) distribution.

The probability density function of the normal distribution, first
derived by De Moivre and 200 years later by both Gauss and Laplace
independently [2]_, is often called the bell curve because of
its characteristic shape (see the example below).

The normal distributions occurs often in nature.  For example, it
describes the commonly occurring distribution of samples influenced
by a large number of tiny, random disturbances, each with its own
unique distribution [2]_.

Parameters
----------
loc : float or array_like of floats
    Mean ("centre") of the distribution.
scale : float or array_like of floats
    Standard deviation (spread or "width") of the distribution. Must be
    non-negative.
size : int or tuple of ints, optional
    Output shape.  If the given shape is, e.g., ``(m, n, k)``, then
    ``m * n * k`` samples are drawn.  If size is ``None`` (default),
    a single v

**array containing random values between 0 and 10:**

In [19]:
np.random.randint(0,10, (2,2))

array([[4, 4],
       [1, 6]])

**array containing only 1s in its :**

Köşegen elemanları 1 olan identity matris oluşturma**

In [20]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Numpy Array Reshaping

* **ndim**: dimesion number
* **shape**: dimesion info
* **size**: total element number
* **dtype**: array data type

In [21]:
import numpy as np

In [22]:
m = np.random.randint(10, size=10)
m

array([3, 5, 0, 9, 0, 7, 0, 7, 9, 1])

In [23]:
m.ndim

1

In [24]:
m.shape

(10,)

In [25]:
m.size

10

In [26]:
m.dtype

dtype('int64')

In [27]:
n = np.random.randint(10, size=(10,5))
n

array([[9, 6, 7, 1, 5],
       [0, 1, 2, 8, 1],
       [1, 7, 6, 4, 4],
       [2, 8, 0, 9, 6],
       [7, 8, 1, 6, 0],
       [0, 2, 0, 7, 0],
       [4, 7, 3, 9, 9],
       [0, 7, 3, 8, 0],
       [3, 9, 7, 4, 2],
       [8, 3, 4, 9, 9]])

In [28]:
n.ndim

2

In [29]:
n.shape

(10, 5)

In [30]:
n.size

50

In [31]:
n.dtype

dtype('int64')

**reshape operations -> creating matrix from vector etc.**

In [32]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
x = np.array([1,2,3])
x

array([1, 2, 3])

In [35]:
x.ndim

1

In [36]:
y = x.reshape((1,3))
y

array([[1, 2, 3]])

In [37]:
y.ndim

2

In [38]:
x[np.newaxis, :]

array([[1, 2, 3]])

In [39]:
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

## Array concatenate

**one dimension:**

In [40]:
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [41]:
a2 = np.array([4,5,6])
a2

array([4, 5, 6])

In [42]:
np.concatenate([a1,a2])

array([1, 2, 3, 4, 5, 6])

In [43]:
l1 = [7,8]

In [44]:
np.concatenate([a1,a2,l1])

array([1, 2, 3, 4, 5, 6, 7, 8])

In [45]:
m1 = np.array([[1,2,3],
              [7,8,9]])
m1

array([[1, 2, 3],
       [7, 8, 9]])

**two dimension:**

In [46]:
np.concatenate([m1,m1])

array([[1, 2, 3],
       [7, 8, 9],
       [1, 2, 3],
       [7, 8, 9]])

In [47]:
np.concatenate([m1,m1], axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [7, 8, 9, 7, 8, 9]])

**different dimensions:**

In [48]:
a2

array([4, 5, 6])

In [49]:
m1

array([[1, 2, 3],
       [7, 8, 9]])

In [50]:
np.vstack([a2,m1])

array([[4, 5, 6],
       [1, 2, 3],
       [7, 8, 9]])

In [51]:
a3 = np.array([[99],
             [98]])
a3

array([[99],
       [98]])

In [52]:
np.hstack([a3,m1])

array([[99,  1,  2,  3],
       [98,  7,  8,  9]])

**vstack merges based on columns; hstack merges based on rows. So; arrays must have same column number for vstack and same row number for hstack!**

## Array splitting

In [53]:
a4 = [1,2,3,43,67,89,96]
a4

[1, 2, 3, 43, 67, 89, 96]

In [54]:
np.split(a4, [3,5])

[array([1, 2, 3]), array([43, 67]), array([89, 96])]

**assigning:**

In [55]:
y1,y2,y3 = np.split(a4, [3,5])

In [56]:
y1

array([1, 2, 3])

In [57]:
y2

array([43, 67])

In [58]:
y3

array([89, 96])

**row-based splitting and adding:**

In [59]:
a6 = np.arange(16).reshape((4,4))
a6

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [60]:
np.vsplit(a6, [2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [61]:
up, down = np.vsplit(a6, [2])

In [62]:
up

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [63]:
down

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

**column-based splitting and adding:**

In [64]:
a6

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [65]:
np.hsplit(a6, [2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [66]:
left, right = np.hsplit(a6, [2])

In [67]:
right

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [68]:
left

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

## Array sorting

In [69]:
v = np.array([4,2,8,6,5,1,7,3])
v

array([4, 2, 8, 6, 5, 1, 7, 3])

In [70]:
np.sort(v)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [71]:
v

array([4, 2, 8, 6, 5, 1, 7, 3])

**in order to make change in vector:**

In [72]:
v.sort()

In [73]:
v

array([1, 2, 3, 4, 5, 6, 7, 8])

**to learn which element is gone to which index:**

In [74]:
v2 = np.array([4,1,5,3,2])
v2

array([4, 1, 5, 3, 2])

In [75]:
np.sort(v2)

array([1, 2, 3, 4, 5])

In [76]:
i = np.argsort(v2)
i

array([1, 4, 3, 0, 2])

In [77]:
v2

array([4, 1, 5, 3, 2])

In [78]:
v2[i]

array([1, 2, 3, 4, 5])

# Numpy Operations

## Index

In [79]:
elis1 = np.random.randint(10, size=10)
elis1

array([4, 5, 7, 3, 7, 1, 1, 7, 8, 2])

In [80]:
elis1[1]

5

In [81]:
elis1[-2]

8

In [82]:
elis1[0]

4

In [83]:
elis2 = np.random.randint(10, size=(3,5))
elis2

array([[5, 6, 0, 0, 2],
       [4, 2, 1, 5, 1],
       [1, 3, 1, 9, 2]])

In [84]:
elis2[0,0]

5

In [85]:
elis2[1,1]

2

In [86]:
elis2[0,0] = 1

In [87]:
elis2[0,0]

1

In [88]:
elis2[0,0] = 3.2

In [89]:
elis2[0,0]

3

## Slice

In [90]:
sli1 = np.arange(20,30)
sli1

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [91]:
sli1[0:3]

array([20, 21, 22])

In [92]:
sli1[3:]

array([23, 24, 25, 26, 27, 28, 29])

In [93]:
sli1[::2]

array([20, 22, 24, 26, 28])

In [94]:
sli1[1::2]

array([21, 23, 25, 27, 29])

In [95]:
sli1[2::2]

array([22, 24, 26, 28])

In [96]:
sli1[1::3]

array([21, 24, 27])

In [97]:
sli2 = np.random.randint(10, size=(5,5))
sli2

array([[7, 6, 7, 5, 6],
       [7, 1, 2, 2, 5],
       [1, 3, 0, 1, 2],
       [2, 8, 2, 1, 9],
       [1, 4, 9, 2, 0]])

**to get a particular column:**

In [98]:
sli2[:,0]

array([7, 7, 1, 2, 1])

In [99]:
sli2[:,0]

array([7, 7, 1, 2, 1])

**to get a particular row:**

In [100]:
sli2[0]

array([7, 6, 7, 5, 6])

In [101]:
sli2[4,:]

array([1, 4, 9, 2, 0])

**to get particula row and column:**

In [102]:
sli2[:2,:3]

array([[7, 6, 7],
       [7, 1, 2]])

In [103]:
sli2[0:2,0:3]

array([[7, 6, 7],
       [7, 1, 2]])

**to get all rows and first 2 columns:**

In [104]:
sli2[:,:2]

array([[7, 6],
       [7, 1],
       [1, 3],
       [2, 8],
       [1, 4]])

In [105]:
sli2[1:3,0:2]

array([[7, 1],
       [1, 3]])

**Note:** If you take a subset and do an assignment to this subset, original matrix will also be changed!!!

In [106]:
sli2

array([[7, 6, 7, 5, 6],
       [7, 1, 2, 2, 5],
       [1, 3, 0, 1, 2],
       [2, 8, 2, 1, 9],
       [1, 4, 9, 2, 0]])

In [107]:
alt_sli2 = sli2[0:3,0:2]
alt_sli2

array([[7, 6],
       [7, 1],
       [1, 3]])

In [108]:
alt_sli2[0,1] = 9999
alt_sli2

array([[   7, 9999],
       [   7,    1],
       [   1,    3]])

In [109]:
sli2

array([[   7, 9999,    7,    5,    6],
       [   7,    1,    2,    2,    5],
       [   1,    3,    0,    1,    2],
       [   2,    8,    2,    1,    9],
       [   1,    4,    9,    2,    0]])

**in order to avoid change in the original matrix; use copy():**

In [110]:
altb_sli2 = sli2[0:3,0:2].copy()
altb_sli2

array([[   7, 9999],
       [   7,    1],
       [   1,    3]])

In [111]:
altb_sli2[0,0] = 8888
altb_sli2

array([[8888, 9999],
       [   7,    1],
       [   1,    3]])

In [112]:
sli2

array([[   7, 9999,    7,    5,    6],
       [   7,    1,    2,    2,    5],
       [   1,    3,    0,    1,    2],
       [   2,    8,    2,    1,    9],
       [   1,    4,    9,    2,    0]])

## Fancy index

In [113]:
fan1 = np.arange(0,30,3)
fan1

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [114]:
fan1[1]

3

In [115]:
[fan1[1], fan1[3]]

[3, 9]

In [116]:
fanalt1 = [1,3,5]

In [117]:
fan1[fanalt1]

array([ 3,  9, 15])

**fancy for 2 dim:**

In [118]:
fan2 = np.arange(9).reshape((3,3))
fan2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [119]:
row1 = np.array([0,1])
col1 = np.array([1,2])

In [120]:
fan2[row1, col1]

array([1, 5])

In [121]:
fan2[0, [1,2]]

array([1, 2])

In [122]:
fan2[0:, [1,2]]

array([[1, 2],
       [4, 5],
       [7, 8]])

**assigning:**

In [123]:
fan3 = np.arange(10)
fan3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [124]:
index1 = np.array([0,1,2])
index1

array([0, 1, 2])

In [125]:
fan3[index1] = 99

In [126]:
fan3

array([99, 99, 99,  3,  4,  5,  6,  7,  8,  9])

In [127]:
fan3[[0,1]] = [4,6]

In [128]:
fan3

array([ 4,  6, 99,  3,  4,  5,  6,  7,  8,  9])

## Conditional operations

In [129]:
kos1 = np.array([1,2,3,4,5])

In [130]:
kos1 > 3

array([False, False, False,  True,  True])

In [131]:
kos1 < 3

array([ True,  True, False, False, False])

In [132]:
kos1 <= 3

array([ True,  True,  True, False, False])

In [133]:
kos1 == 3

array([False, False,  True, False, False])

In [134]:
kos1 != 3

array([ True,  True, False,  True,  True])

In [135]:
kos1[kos1 > 3]

array([4, 5])

In [136]:
(2*kos1)

array([ 2,  4,  6,  8, 10])

In [137]:
(kos1**2) 

array([ 1,  4,  9, 16, 25])

In [138]:
(2*kos1) == (kos1**2)

array([False,  True, False, False, False])

In [139]:
kos2 = np.array([1,2,3,4,5])

In [140]:
np.equal(3, kos2)

array([False, False,  True, False, False])

In [141]:
np.equal([0,1,3], np.arange(3))

array([ True,  True, False])

In [142]:
np.arange(3)

array([0, 1, 2])

In [143]:
kos3 = np.random.randint(0, 10, (3,3))
kos3

array([[1, 9, 1],
       [3, 1, 9],
       [8, 3, 0]])

In [144]:
kos3 > 5

array([[False,  True, False],
       [False, False,  True],
       [ True, False, False]])

In [145]:
np.sum(kos3 > 5)

3

In [146]:
np.sum((kos3 > 3) & (kos3 < 7))

0

In [147]:
(kos3 > 3) & (kos3 < 7)

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [148]:
np.sum((kos3 > 3) | (kos3 < 7))

9

In [149]:
np.sum(kos3 > 4, axis = 1)

array([1, 1, 1])

In [150]:
np.sum(kos3 > 4, axis = 0)

array([1, 1, 1])

all & any

In [151]:
np.all(kos3 > 4)

False

In [152]:
np.all(kos3 >= 0)

True

In [153]:
np.any(kos3 > 4)

True

In [154]:
np.all(kos3 > 4, axis = 0)

array([False, False, False])

In [155]:
np.all(kos3 > 4, axis = 1)

array([False, False, False])

In [156]:
kos4 = np.array([1,2,3,4,5])
kos4

array([1, 2, 3, 4, 5])

In [157]:
kos4[0]

1

In [158]:
kos4 > 3

array([False, False, False,  True,  True])

In [159]:
kos4[kos4 > 3]

array([4, 5])

In [160]:
kos4[(kos4 > 1) & (kos4 < 5)]

array([2, 3, 4])

## Mathematical operations

In [161]:
mat1 = np.arange(5)
mat1

array([0, 1, 2, 3, 4])

In [162]:
mat1 - 1

array([-1,  0,  1,  2,  3])

In [163]:
mat1 / 2

array([0. , 0.5, 1. , 1.5, 2. ])

In [164]:
mat1 * 5

array([ 0,  5, 10, 15, 20])

In [165]:
mat1 ** 2

array([ 0,  1,  4,  9, 16])

In [166]:
mat1 % 2

array([0, 1, 0, 1, 0])

In [167]:
5*(mat1/2*9)

array([ 0. , 22.5, 45. , 67.5, 90. ])

In [168]:
np.add(mat1, 2)

array([2, 3, 4, 5, 6])

In [169]:
np.subtract(mat1,1)

array([-1,  0,  1,  2,  3])

In [170]:
np.multiply(mat1,3)

array([ 0,  3,  6,  9, 12])

In [171]:
np.divide(mat1,3)

array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333])

In [172]:
np.power(mat1,2)

array([ 0,  1,  4,  9, 16])

In [173]:
mat2 = np.arange(1,6)
mat2

array([1, 2, 3, 4, 5])

In [174]:
np.add.reduce(mat2)

15

In [175]:
np.add.accumulate(mat2)

array([ 1,  3,  6, 10, 15])

In [176]:
mat3 = np.random.normal(0,1,30)
mat3

array([-0.63229961, -1.85507676,  1.34306185,  0.42590341, -0.55008856,
        0.27063991,  0.72212283,  1.09374117,  0.01087247, -0.92633472,
        1.11301396, -0.0868282 , -0.13915778,  0.07343249,  0.03279182,
       -0.31009841, -0.90827374,  0.38625984, -2.25162422,  1.01908727,
        0.04515654,  0.22116344,  1.57183062, -0.21290018, -0.7858235 ,
        0.56944061,  1.68858479, -0.13709464, -0.50761276, -1.19899226])

In [177]:
np.mean(mat3)

0.002829922597859554

In [178]:
np.std(mat3)

0.918382441545852

In [179]:
np.var(mat3)

0.8434263089397203

In [180]:
np.median(mat3)

0.021832144609958876

In [181]:
sum(mat3)

0.08489767793578662

**in order to consider missing values for run:**

np.nanmean()

np.nanstd()

np.nanvar()

np.nanrgmin()

np.nanrgmax()

np.nanmedian()

In [182]:
np.max(mat3)

1.6885847891920003

In [183]:
np.min(mat3)

-2.251624216369555

**Mathematical operations for 2 dim arrays:**

In [184]:
mat4 = np.random.normal(0,1,(3,3))
mat4

array([[-1.05229317, -0.78397344,  1.46529002],
       [-0.21603631, -0.13996866,  2.07079603],
       [-1.37585963, -1.62240325, -0.22489954]])

In [185]:
mat4.sum()

-1.8793479393944894

**sum based on column:**

In [186]:
mat4.sum(axis = 0)

array([-2.64418911, -2.54634534,  3.31118651])

**sum based on row:**

In [187]:
mat4.sum(axis = 1)

array([-0.37097659,  1.71479106, -3.22316241])

# Broadcasting - Operations on Arrays with Different Dimensions

In [188]:
bro1 = np.array([1,2,3])
bro2 = np.array([1,2,3])
bro1 + bro2

array([2, 4, 6])

In [189]:
bro3 = np.ones((3,3))
bro3

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [190]:
bro1 + bro3

array([[2., 3., 4.],
       [2., 3., 4.],
       [2., 3., 4.]])

In [191]:
bro4 = np.arange(3)
bro4

array([0, 1, 2])

In [192]:
bro5 = np.arange(3)[:, np.newaxis]
bro5

array([[0],
       [1],
       [2]])

In [193]:
bro4 + bro5

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [194]:
bro6 = np.arange(3).reshape((3,1))
bro6

array([[0],
       [1],
       [2]])

In [195]:
bro7 = np.arange(3)
bro7

array([0, 1, 2])

In [196]:
bro6.shape

(3, 1)

In [197]:
bro7.shape

(3,)

In [198]:
bro6 + bro7

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [199]:
bro8 = np.ones((3,2))
bro8

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [200]:
bro9 = np.arange(3)
bro9

array([0, 1, 2])

In [201]:
bro8.shape

(3, 2)

In [202]:
bro9.shape

(3,)

**in that case; broadcast does not work:**

In [203]:
bro8 + bro9

ValueError: operands could not be broadcast together with shapes (3,2) (3,) 

# Numpy structural arrays

In [204]:
name1 = ['joe', 'elly', 'lisa']
age1 = [25, 22, 19]
height1 = [168, 159, 172]

In [205]:
data1 = np.zeros(3, dtype={'names':('name1', 'age1', 'height1'),
                          'formats':('U10', 'i4', 'f8')})

In [206]:
data1

array([('', 0, 0.), ('', 0, 0.), ('', 0, 0.)],
      dtype=[('name1', '<U10'), ('age1', '<i4'), ('height1', '<f8')])

In [207]:
data1['name1'] = name1
data1['age1'] = age1
data1['height1'] = height1

In [208]:
data1

array([('joe', 25, 168.), ('elly', 22, 159.), ('lisa', 19, 172.)],
      dtype=[('name1', '<U10'), ('age1', '<i4'), ('height1', '<f8')])

In [209]:
data1['name1']

array(['joe', 'elly', 'lisa'], dtype='<U10')

In [210]:
data1[0]

('joe', 25, 168.)

In [211]:
data1[data1['age1']<25]['name1']

array(['elly', 'lisa'], dtype='<U10')

# References

https://numpy.org/

udemy.com / Data Science and Machine Learning

coursera.com / Python for Genomic Data Science